
//! Autogenerated weights for `pallet_multisend`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-08, STEPS: `1`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/omniblock-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_multisend
// --extrinsic
// *
// --repeat
// 10
// --json
// --output
// ./pallets/multisend/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_multisend`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_multisend::WeightInfo for WeightInfo<T> {
	// Storage: System Account (r:50 w:50)
	fn send_tokens_to_multiple_receivers() -> Weight {
		(517_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(50 as Weight))
			.saturating_add(T::DbWeight::get().writes(50 as Weight))
	}
}
